### ISSUE TITLE
Temperature plot improvements

### ISSUE THREAD

**Issue by cgevans** [cgevans/qslib#8]
It would be useful to have the temperature plot become a more general "experiment timeline" plot.  Some potential elements:

- [ ] Shaded regions for pauses/resumes.
- [ ] Shaded regions for opened drawer.
- [ ] Shaded regions for raised cover.
- [ ] Red lines / etc for errors, scheduler faults, power failures.
- [ ] Lines for protocol changes.
- [ ] Intended protocol, for comparison.
